// TODO(vista-dai-pini): luoghi copiati da casa-nei-pini, da sostituire con quelli reali.
// Dati strutturali (indirizzo, telefono, coordinate, link Maps) dei luoghi nei
// dintorni. Le descrizioni tradotte vivono in translations/*.js sotto
// pages.dintorni.places. Le coordinate sono usate per le mini mappe per
// categoria in Dintorni.jsx; dove assenti (es. "villaraba", non geocodificabile)
// il luogo compare comunque in lista ma non sulla mappa.
const nearbyPlaces = [
  {
    id: "pizzerie",
    icon: "Pizza",
    places: [
      {
        id: "p400gradi",
        name: "400 Gradi Pizzeria Ristorante",
        address: "Via Giuseppe Verdi 1, Varazze",
        phone: "+39 350 143 9496",
        lat: 44.361414,
        lon: 8.578348,
        mapsUrl: "https://maps.google.com/?q=400+Gradi+Pizzeria+Via+Giuseppe+Verdi+Varazze",
      },
      {
        id: "ilGombo",
        name: "Il Gombo",
        address: "Via Emilio Vecchia 140, Varazze",
        phone: "019 918599",
        lat: 44.376056,
        lon: 8.565859,
        mapsUrl: "https://maps.google.com/?q=Il+Gombo+Via+Emilio+Vecchia+Varazze",
      },
      {
        id: "kursaal",
        name: "Kursaal Margherita",
        address: "Corso Matteotti 15, Varazze",
        phone: "+39 345 762 2779",
        lat: 44.358563,
        lon: 8.575903,
        mapsUrl: "https://maps.google.com/?q=Kursaal+Margherita+Corso+Matteotti+Varazze",
      },
      {
        id: "rugantino",
        name: "Ristorante Pizzeria Il Rugantino",
        address: "Via Guido Damele 8, Varazze",
        phone: "019 934832",
        lat: 44.360422,
        lon: 8.577114,
        mapsUrl: "https://maps.google.com/?q=Ristorante+Pizzeria+Il+Rugantino+Varazze",
      },
    ],
  },
  {
    id: "pesce",
    icon: "Fish",
    places: [
      {
        id: "pescePazzo",
        name: "Il Pesce Pazzo",
        address: "Via dei Maestri d'Ascia 1, Marina di Varazze",
        phone: "+39 342 803 6593",
        lat: 44.35365,
        lon: 8.566135,
        mapsUrl: "https://maps.google.com/?q=Il+Pesce+Pazzo+Marina+di+Varazze",
      },
      {
        id: "alSolitoPosto",
        name: "Al Solito Posto",
        address: "Via Santa Caterina 29-30, Varazze",
        phone: "019 2046537",
        lat: 44.359875,
        lon: 8.581662,
        mapsUrl: "https://maps.google.com/?q=Al+Solito+Posto+Varazze",
      },
      {
        id: "acquaESale",
        name: "Acqua e Sale Bistrot Creativo",
        address: "Varazze",
        lat: 44.3585,
        lon: 8.575,
        mapsUrl: "https://maps.google.com/?q=Acqua+e+Sale+Bistrot+Varazze",
      },
      {
        id: "fishHouse",
        name: "Fish House Restaurant",
        address: "Varazze",
        lat: 44.3592,
        lon: 8.5775,
        mapsUrl: "https://maps.google.com/?q=Fish+House+Restaurant+Varazze",
      },
      {
        id: "calaTorcida",
        name: "Cala Torcida",
        address: "Varazze",
        lat: 44.376188,
        lon: 8.628513,
        mapsUrl: "https://maps.google.com/?q=Cala+Torcida+Varazze",
      },
      {
        id: "pescoei",
        name: "Pescoei Bistrot",
        address: "Via San Celso 1-3, Varazze",
        lat: 44.356997,
        lon: 8.569205,
        mapsUrl: "https://maps.google.com/?q=Pescoei+Bistrot+Varazze",
      },
    ],
  },
  {
    id: "bar",
    icon: "Coffee",
    places: [
      {
        id: "gattoNero",
        name: "Cafè Gatto Nero",
        address: "Piazza Dante Alighieri 21, Varazze",
        phone: "019 450 9562",
        lat: 44.359584,
        lon: 8.578356,
        mapsUrl: "https://maps.google.com/?q=Cafè+Gatto+Nero+Piazza+Dante+Varazze",
      },
      {
        id: "ebrezza",
        name: "E.brezza Enoteca Wine Bar",
        address: "Piazza Dante Alighieri 25-26, Varazze",
        phone: "019 933674",
        lat: 44.359684,
        lon: 8.578456,
        mapsUrl: "https://maps.google.com/?q=Ebrezza+Enoteca+Wine+Bar+Piazza+Dante+Varazze",
      },
      {
        id: "laBeffa",
        name: "La Beffa",
        address: "Piazza Fabrizio de André, Varazze",
        lat: 44.356999,
        lon: 8.5694,
        mapsUrl: "https://maps.google.com/?q=La+Beffa+Piazza+Fabrizio+de+Andrè+Varazze",
      },
      {
        id: "daRettaAllaMola",
        name: "Bar Da Retta alla Mola",
        address: "Lungomare, Varazze",
        lat: 44.359859,
        lon: 8.585425,
        mapsUrl: "https://maps.google.com/?q=Bar+Da+Retta+alla+Mola+Varazze",
      },
    ],
  },
  {
    id: "spiagge",
    icon: "Umbrella",
    places: [
      {
        id: "lungomareEuropa",
        name: "Lungomare Europa",
        lat: 44.362962,
        lon: 8.598722,
        mapsUrl: "https://maps.google.com/?q=Lungomare+Europa+Varazze",
      },
      {
        id: "spiaggePonente",
        name: "Spiagge zona Ponente",
        lat: 44.3555,
        lon: 8.559,
        mapsUrl: "https://maps.google.com/?q=Spiaggia+Ponente+Varazze",
      },
      {
        id: "marinaVarazze",
        name: "Marina di Varazze",
        lat: 44.352086,
        lon: 8.568274,
        mapsUrl: "https://maps.google.com/?q=Marina+di+Varazze",
      },
      {
        id: "celleLigure",
        name: "Celle Ligure",
        lat: 44.346324,
        lon: 8.544434,
        mapsUrl: "https://maps.google.com/?q=Celle+Ligure",
      },
    ],
  },
  {
    id: "supermercati",
    icon: "ShoppingCart",
    places: [
      {
        id: "ekom",
        name: "Ekom",
        address: "Via Maestri del Lavoro 52, Varazze",
        lat: 44.354166,
        lon: 8.564863,
        mapsUrl: "https://maps.google.com/?q=Ekom+Via+Maestri+del+Lavoro+Varazze",
      },
      {
        id: "carrefourExpress",
        name: "Carrefour Express",
        address: "Varazze",
        lat: 44.358705,
        lon: 8.573347,
        mapsUrl: "https://maps.google.com/?q=Carrefour+Express+Varazze",
      },
      {
        id: "coop",
        name: "Coop",
        address: "Via Santa Caterina 49, Varazze",
        lat: 44.365569,
        lon: 8.573799,
        mapsUrl: "https://maps.google.com/?q=Coop+Via+Santa+Caterina+Varazze",
      },
      {
        id: "mercatoSettimanale",
        name: "Mercato settimanale",
        address: "Davanti al Comune, Varazze",
        lat: 44.359911,
        lon: 8.576354,
        mapsUrl: "https://maps.google.com/?q=Mercato+Varazze",
      },
    ],
  },
  {
    id: "attrazioni",
    icon: "Compass",
    places: [
      {
        id: "santuarioGuardia",
        name: "Santuario di Nostra Signora della Guardia",
        lat: 44.372731,
        lon: 8.595174,
        mapsUrl: "https://maps.google.com/?q=Santuario+Nostra+Signora+Guardia+Varazze",
      },
      {
        id: "parcoBeigua",
        name: "Parco Naturale del Beigua",
        lat: 44.47904,
        lon: 8.671737,
        mapsUrl: "https://maps.google.com/?q=Parco+Naturale+del+Beigua",
      },
      {
        id: "surf",
        name: "Surf e sport acquatici",
        lat: 44.359407,
        lon: 8.576125,
        mapsUrl: "https://maps.google.com/?q=Molo+del+Surf+Varazze",
      },
      {
        id: "pistaCiclabile",
        name: "Pista ciclabile Varazze–Cogoleto",
        lat: 44.356599,
        lon: 8.566659,
        mapsUrl: "https://maps.google.com/?q=pista+ciclabile+Varazze+Cogoleto",
      },
      {
        id: "centroStorico",
        name: "Centro storico di Varazze",
        lat: 44.359808,
        lon: 8.579908,
        mapsUrl: "https://maps.google.com/?q=Centro+storico+Varazze",
      },
      {
        id: "albissola",
        name: "Albissola Marina",
        lat: 44.327272,
        lon: 8.50319,
        mapsUrl: "https://maps.google.com/?q=Albissola+Marina",
      },
      {
        id: "savona",
        name: "Savona",
        lat: 44.304542,
        lon: 8.483753,
        mapsUrl: "https://maps.google.com/?q=Savona+centro",
      },
      {
        id: "genova",
        name: "Genova",
        lat: 44.40937,
        lon: 8.927403,
        mapsUrl: "https://maps.google.com/?q=Genova+Porto+Antico",
      },
    ],
  },
];

export default nearbyPlaces;
